### ISSUE TITLE
redeem bulk coupon

### ISSUE THREAD

**Issue by gagalago** [recurly/recurly-client-ruby#284]
I can't redeem a bulk coupon code
```ruby
coupon = Recurly::Coupon.find(bulk_coupon_code)
coupon.redeem(billing_account)
```
the error 
```
NoMethodError: undefined method `new' for []:Array
	from /home/sigo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/recurly-2.7.4/lib/recurly/coupon.rb:76:in `redeem'
	from (irb):4
	from /home/sigo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /home/sigo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /home/sigo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/sigo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/sigo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

I think the problem is that bulk coupon don't have pager of redemptions.

If someone give me some hint of how to solve that. I can try to propose a pull request with the correction.

**Comment by bhelx** [comment]
@gagalago thanks for reporting. I'm going to see if i can reproduce this today. If I can, I should be able to patch it pretty quick.

**Comment by bhelx** [comment]
I was able to reproduce this. I will have a fix ready by tonight.

**Comment by gagalago** [comment]
thanks a lot

**Comment by bhelx** [comment]
@gagalago I'll go ahead and do a `2.7.5` bump today. It will be linked back here.
